version: '3.9'

services:
  web:
    build: .
    container_name: barrovivo_app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn Barrovivo.wsgi:application --bind 0.0.0.0:8080 --workers 3"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-storage.json
    volumes:
      - ./gcp-storage.json:/app/gcp-storage.json  # Clave del bucket GCP
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: barrovivo_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
