# Generated by Django 5.2.4 on 2025-09-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apto_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
